[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = true
host = '0.0.0.0'
port = 3031

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'test-0'
rpc_addr = 'http://localhost:16657'
grpc_addr = 'http://localhost:9095'
websocket_addr = 'ws://localhost:16657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'hermes-rly0'
store_prefix = 'ibc'
max_gas = 4000000
gas_price = { price = 0.025, denom = 'uatom' }
gas_multiplier = 1.5
clock_drift = '1m' # to accomdate docker containers
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'test-1'
rpc_addr = 'http://localhost:26657'
grpc_addr = 'http://localhost:9096'
websocket_addr = 'ws://localhost:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'hermes-rly1'
store_prefix = 'ibc'
max_gas =  4000000
gas_price = { price = 0.025, denom = 'uatom' }
gas_multiplier = 1.5
clock_drift = '1m' # to accomdate docker containers
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
