name: Check Markdown links
on: 
  workflow_dispatch:
  schedule: 
    - cron: '* */24 * * *'
jobs:
  markdown-link-check:
    runs-on: depot-ubuntu-22.04-4
    steps:
      - uses: actions/checkout@v6
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
        with:
          folder-path: "docs"
          file-extension: ".mdx"