name: Release Sims
on:
  pull_request:
    branches:
      - "rc**"

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-sims')"
    steps:
      - uses: actions/checkout@v3.2.0
      - run: |
          make build

  newbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.18
      - name: Install runsim
        run: go install github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v3.0.10
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  install-runsim:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: install runsim
        run: go install github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v3.0.10
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  test-sim-multi-seed-long:
    runs-on: ubuntu-latest
    needs: [build, install-runsim]
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: actions/cache@v3.0.10
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test-sim-multi-seed-long
        run: |
          make test-sim-multi-seed-long

  test-sim-nondeterminism:
    runs-on: ubuntu-latest
    needs: newbuild
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.18
      - uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/cache@v3.0.10
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: "env.GIT_DIFF != ''"
      - name: test nondeterminism
        run: |
          make test-sim-nondeterminism
        if: "env.GIT_DIFF != ''"
