name: SimLabeled
on:
  pull_request:
    types: [ labeled ]

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  newbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.16
      - name: Install runsim
        run: export GO111MODULE="on" && go get github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v3.0.4
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  test-sim-nondeterminism-labeled:
    if: ${{ github.event.label.name == 'sim' }}
    runs-on: ubuntu-latest
    needs: newbuild
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.16
      - uses: actions/cache@v3.0.4
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test nondeterminism
        run: |
          make test-sim-nondeterminism
